apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-minikube
  name: hello-minikube
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
    # nodePort: 32381 - if not enabled, kubernetes assigns a random node port
  selector:
    app: hello-minikube
  type: NodePort
