apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-go-api
  name: simple-go-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-go-api
  template:
    metadata:
      labels:
        app: simple-go-api
    spec:
      containers:
      - image: baranbartu/simple-go-api:v1
        name: simple-go-api
        ports:
        - containerPort: 8080
          protocol: TCP
