apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-go-api-secret-volume
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-go-api-secret-volume
  template:
    metadata:
      labels:
        app: simple-go-api-secret-volume
    spec:
      containers:
      - name: simple-go-api-secret-volume
        image: baranbartu/simple-go-api:v1
        ports:
        - name: cont-port
          containerPort: 8001
        volumeMounts:
        - name: creds-volume
          mountPath: /etc/creds
          readOnly: true
        env:
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: username-password
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: username-password
                key: password
      volumes:
      - name: creds-volume
        secret:
          secretName: username-password
